# HTTP Test requests for hybrid servers

### Variables
@mediaServer = http://localhost:3000/api/v1
@authServer = http://localhost:3001/api/v1
@uploadServer = http://localhost:3002/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJsZXZlbF9uYW1lIjoiVXNlciIsImlhdCI6MTc2ODM4MjU0OX0.H_PTqA32bSDYCMOnqrkDi3iDPYDgGfVDGQymox3f50E

### Auth server

### Register
POST @{{authServer}}/users
Content-Type: application/json

{
    "username": "suvi",
    "password": "kalakana",
    "email": "suvi@example.com"
}

### Login
POST @{{authServer}}/auth/login
Content-Type: application/json

{
    "username": "suvi",
    "password": "kalakana"
}

##################

### Media API

### Get media
GET @{{mediaServer}}/media?page=1&limit=10

##################

### Upload server

### Upload file
POST @{{uploadServer}}/upload
Content-Type: multipart/form-data; boundary=Boundary
Authorization: Bearer @{{token}}

--Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./test-cat.png
--Boundary--